### ISSUE TITLE
regarding the functionality of each py file

### ISSUE THREAD

**Issue by wenouyang** [tkuanlun350/Tensorflow-SegNet#1]
Hello, thanks for sharing the code. Would you like to give some explanation on the functionality of each py file, e.g., what does seq_slice.py do?

**Comment by tkuanlun350** [comment]
Sure, I will try to make my code easier to understand. I am currently occupied by some research work, I will refactor my model and put more comment as soon as possible .

**Comment by tkuanlun350** [comment]
README is updated now
