### ISSUE TITLE
About model checkpoint

### ISSUE THREAD

**Issue by vuhoangminh** [tkuanlun350/Tensorflow-SegNet#3]
Hello,

Thank you for your hard work.

I am new to Tensorflow, so I am writing to ask for your help about check point file.

In the bash file, you mention about:
"--finetune=/tmp3/first350/TensorFlow/Logs/model.ckpt-1000"

Could you please guide me how to get the model.ckpt?

Thank you so much for your help.

**Comment by tkuanlun350** [comment]
Hi, the checkpoint should be save automatically in your log_dir, you can refer to model.py line 350 for specify log_dir, line 468 for saving ckpt file

**Comment by vuhoangminh** [comment]
Hi,

I got it. Thank you so much for your time.
